openapi: 3.0.0
info:
  title: Bulk edit API
  version: v1
servers:
  - url: /marc-export/
paths:
  /upload:
    post:
      description: Upload csv or cql file
      operationId: uploadFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: File uploaded
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
components:
  schemas:
    errors:
      $ref: '../../../../folio-export-common/schemas/common/errors.json#/Errors'
  examples:
    errors:
      value:
        $ref: '../../../../folio-export-common/examples/errors.sample'
