openapi: 3.0.0
info:
  title: Entities-links export schemas
  version: v1
servers:
  - url: https://stub.com/
paths:
  /stub:
    get:
      responses:
        "200":
          description: stub
components:
  schemas:
    authorityControlExportConfig:
      $ref: '../../../../folio-export-common/schemas/authority-control/authorityControlExportConfig.json#/AuthorityControlExportConfig'
    authorityDataStatDto:
      $ref: '../../../../folio-export-common/schemas/authority-control/authorityDataStatDto.json#/AuthorityDataStatDto'
    instanceDataStatDto:
      $ref: '../../../../folio-export-common/schemas/authority-control/instanceDataStatDto.json#/InstanceDataStatDto'
    authorityDataStatDtoCollection:
      $ref: '../../../../folio-export-common/schemas/authority-control/authorityDataStatDtoCollection.json#/AuthorityDataStatDtoCollection'
    instanceDataStatDtoCollection:
      $ref: '../../../../folio-export-common/schemas/authority-control/instanceDataStatDtoCollection.json#/InstanceDataStatDtoCollection'
