openapi: 3.0.0
info:
  title: Bulk edit API
  version: v1
servers:
  - url: /bulk-edit/
paths:
  /{jobId}/item-content-update/upload:
    post:
      description: Upload item content updates
      operationId: postItemContentUpdates
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: false
          schema:
            type: integer
          description: The numbers of records to return
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/itemContentUpdateCollection"
      responses:
        "200":
          description: Collection of items for preview
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/itemCollection"
        "400":
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "404":
          description: Not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/user-content-update/upload:
    post:
      description: Upload user content updates
      operationId: postUserContentUpdates
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: false
          schema:
            type: integer
          description: The numbers of records to return
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/userContentUpdateCollection"
      responses:
        "200":
          description: Collection of users for preview
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userCollection"
        "400":
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "404":
          description: Not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/preview/updated-items/download:
    get:
      description: Download preview as csv-file
      operationId: downloadPreviewByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        '200':
          description: Preview updated of items to download
          content:
            text/csv:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "404":
          description: Not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/preview/users:
    get:
      description: Get a list of users for preview
      operationId: getPreviewUsersByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: true
          schema:
            type: integer
          description: The numbers of users to return
      responses:
        '200':
          description: Collection of users for preview
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/userCollection"
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '404':
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '500':
           description: Internal server errors, e.g. due to misconfiguration
           content:
             application/json:
               example:
                 $ref: "#/components/examples/errors"
               schema:
                 $ref: "#/components/schemas/errors"
  /{jobId}/preview/items:
    get:
      description: Get a list of items for preview
      operationId: getPreviewItemsByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: true
          schema:
            type: integer
          description: The numbers of items to return
      responses:
        '200':
          description: Collection of items for preview
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/itemCollection"
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '404':
          description: Not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/preview/holdings:
    get:
      description: Get a list of holdings for preview
      operationId: getPreviewHoldingsByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: true
          schema:
            type: integer
          description: The numbers of holdings to return
      responses:
        '200':
          description: Collection of holdings for preview
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/holdingsRecordCollection"
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '404':
          description: Not found
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/errors:
    get:
      description: Get a list of errors for preview
      operationId: getErrorsPreviewByJobId
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
        - in: query
          name: limit
          required: true
          schema:
            type: integer
          description: The numbers of users to return
      responses:
        '200':
          description: Collection of users for preview
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        '404':
          description: No found
          content:
            text/plain:
              schema:
                type: string
                example: Job not found
        '500':
          description: Internal server errors, e.g. due to misconfiguration
          content:
            text/plain:
              schema:
                type: string
                example: Internal server error
  /{jobId}/upload:
    post:
      description: Upload csv file
      operationId: uploadCsvFile
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: File uploaded
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/start:
    post:
      description: Start job
      operationId: startJob
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Job is started
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "404":
          description: Bad Request
          content:
            text/plain:
              schema:
                type: string
                example: Job not found
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
  /{jobId}/roll-back:
    post:
      description: Roll back csv file
      operationId: rollBackCsvFile
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
      responses:
        "200":
          description: Csv file roll back uploaded
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
components:
  schemas:
    UUID:
      type: string
      format: uuid
    errors:
      $ref: '../../../../folio-export-common/schemas/common/errors.json#/Errors'
    parameter:
      $ref: '../../../../folio-export-common/schemas/common/parameter.json#/Parameter'
    userGroupCollections:
      $ref: '../../../../folio-export-common/schemas/user/userGroupCollection.json#/UserGroupCollection'
    addressTypeCollection:
      $ref: '../../../../folio-export-common/schemas/user/addressTypeCollection.json#/AddressTypeCollection'
    proxyForCollection:
      $ref: '../../../../folio-export-common/schemas/user/proxyForCollection.json#/ProxyForCollection'
    departmentCollection:
      $ref: '../../../../folio-export-common/schemas/user/departmentCollection.json#/DepartmentCollection'
    userCollection:
      $ref: '../../../../folio-export-common/schemas/user/userCollection.json#/UserCollection'
    itemCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/itemCollection.json#/ItemCollection'
    callNumberType:
      $ref: '../../../../folio-export-common/schemas/inventory/callNumberType.json#/CallNumberType'
    damagedStatus:
      $ref: '../../../../folio-export-common/schemas/inventory/damagedStatus.json#/DamagedStatus'
    noteType:
      $ref: '../../../../folio-export-common/schemas/inventory/itemNoteType.json#/NoteType'
    electronicAccessRelationship:
      $ref: '../../../../folio-export-common/schemas/inventory/electronicAccessRelationship.json#/ElectronicAccessRelationship'
    statisticalCode:
      $ref: '../../../../folio-export-common/schemas/inventory/statisticalCode.json#/StatisticalCode'
    itemLocationCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/locationCollection.json#/ItemLocationCollection'
    callNumberTypes:
      $ref: '../../../../folio-export-common/schemas/inventory/callNumberTypeCollection.json#/CallNumberTypeCollection'
    damagedStatuses:
      $ref: '../../../../folio-export-common/schemas/inventory/damagedStatusCollection.json#/DamagedStatusCollection'
    noteTypes:
      $ref: '../../../../folio-export-common/schemas/inventory/itemNoteTypeCollection.json#/NoteTypeCollection'
    materialTypes:
      $ref: '../../../../folio-export-common/schemas/inventory/materialTypeCollection.json#/MaterialTypeCollection'
    briefHoldings:
      $ref: '../../../../folio-export-common/schemas/inventory/briefHoldingCollection.json#/BriefHoldingsRecordCollection'
    briefInstances:
      $ref: '../../../../folio-export-common/schemas/inventory/briefInstanceCollection.json#/BriefInstanceCollection'
    loanTypes:
      $ref: '../../../../folio-export-common/schemas/inventory/loanTypeCollection.json#/LoanTypeCollection'
    electronicAccessRelationShips:
      $ref: '../../../../folio-export-common/schemas/inventory/electronicAccessRelationshipCollection.json#/ElectronicAccessRelationshipCollection'
    statisticalCodes:
      $ref: '../../../../folio-export-common/schemas/inventory/statisticalCodeCollection.json#/StatisticalCodeCollection'
    itemContentUpdateCollection:
      $ref: '../../../../folio-export-common/schemas/bulk-edit/itemContentUpdateCollection.json#/ItemContentUpdateCollection'
    userContentUpdateCollection:
      $ref: '../../../../folio-export-common/schemas/bulk-edit/userContentUpdateCollection.json#/UserContentUpdateCollection'
    customFieldCollection:
      $ref: '../../../../folio-export-common/schemas/user/customFieldCollection.json#/CustomFieldCollection'
    holdingsRecordCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/holdingsRecordCollection.json#/HoldingsRecordCollection'
    holdingsTypeCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/holdingsTypeCollection.json#/HoldingsTypeCollection'
    holdingsNoteTypeCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/holdingsNoteTypeCollection.json#/HoldingsNoteTypeCollection'
    illPolicyCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/illPolicyCollection.json#/IllPolicyCollection'
    holdingsRecordsSourceCollection:
      $ref: '../../../../folio-export-common/schemas/inventory/holdingsRecordsSourceCollection.json#/HoldingsRecordsSourceCollection'
  examples:
    errors:
      value:
        $ref: '../../../../folio-export-common/examples/errors.sample'
