openapi: 3.0.0
info:
  title: Bulk edit API
  version: v1
servers:
  - url: /data-export-worker/
paths:
  /bulk-edit/{jobId}/upload:
    post:
      description: Upload csv file
      operationId: uploadCsvFile
      parameters:
        - name: jobId
          in: path
          required: true
          description: UUID of the JobCommand
          schema:
            $ref: "#/components/schemas/UUID"
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
      responses:
        "201":
          description: File uploaded
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
        "500":
          description: Internal server errors, e.g. due to misconfiguration
          content:
            application/json:
              example:
                $ref: "#/components/examples/errors"
              schema:
                $ref: "#/components/schemas/errors"
components:
  schemas:
    UUID:
      type: string
      format: uuid
    errors:
      $ref: 'schemas/common/errors.json#/Errors'
  examples:
    errors:
      value:
        $ref: 'examples/errors.sample'
