openapi: 3.0.0
info:
  title: E-holdings export schemas
  version: v1
servers:
  - url: https://stub.com/
paths:
  /stub:
    get:
      responses:
        "200":
          description: stub
components:
  schemas:
    note:
      $ref: '../../../../folio-export-common/schemas/note/note.json#/Note'
    ePackage:
      $ref: '../../../../folio-export-common/schemas/eholdings/e-package/package.json#/EPackage'
    eResource:
      $ref: '../../../../folio-export-common/schemas/eholdings/e-resources/resource.json#/EResource'
    eResources:
      $ref: '../../../../folio-export-common/schemas/eholdings/e-resources/resources.json#/EResources'
    accessTypeData:
      $ref: '../../../../folio-export-common/schemas/eholdings/accessTypes/accessTypeData.json#/AccessTypeData'
