openapi: 3.0.0
info:
  title: Refresh presigned url API
  version: v1
paths:
  /refresh-presigned-url:
    get:
      description: Get presigned Url for export file
      operationId: getRefreshedPresignedUrl
      parameters:
        - in: query
          name: filePath
          required: true
          description: Path to exported file
          schema:
            type: string
      responses:
        '200':
          description: Presigned Url for download
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/presignedUrl"


components:
  schemas:
    presignedUrl:
      $ref: '../../../../folio-export-common/schemas/exportFilePresignedUrl.json#/PresignedUrl'
