ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
DROP COLUMN TYPE_CD,
DROP COLUMN KEY_NAME,
DROP COLUMN STRING_VAL,
DROP COLUMN DATE_VAL,
DROP COLUMN LONG_VAL,
DROP COLUMN DOUBLE_VAL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
ADD PARAMETER_NAME VARCHAR(100) NOT NULL ,
ADD PARAMETER_TYPE VARCHAR(100) NOT NULL ,
ADD PARAMETER_VALUE VARCHAR(2500) NOT NULL ;

