DROP TABLE BATCH_JOB_EXECUTION_PARAMS;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
  JOB_EXECUTION_ID BIGINT NOT NULL ,
  PARAMETER_NAME VARCHAR(100) NOT NULL ,
  PARAMETER_TYPE VARCHAR(100) NOT NULL ,
  PARAMETER_VALUE VARCHAR(2500) ,
  IDENTIFYING CHAR(1) NOT NULL ,
  constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);
